A very custom handhold for the ec2 instance.

diff --git a/git-java/textconv-javap b/git-java/textconv-javap
--- a/git-java/textconv-javap
+++ b/git-java/textconv-javap
@@ -4,8 +4,9 @@
 javapBin=javap
 [[ -x "$javapBin" ]] || javapBin="$JDK_HOME/bin/javap"
 [[ -x "$javapBin" ]] || javapBin="$JAVA_HOME/bin/javap"
+[[ -x "$javapBin" ]] || javapBin="/etc/alternatives/java_sdk/bin/javap"
 [[ -x "$javapBin" ]] || {
-  echo "Cannot locate javap."
+  echo >&2 "Cannot locate javap."
   exit 1
 }
 
